@startuml 演習3-2クラス図
left to right direction

class 医局{}
class 医師{
    ---
    + 診察記録を作る()
    + 診察をする()
}
class 患者{}
class 診察記録{}

医局 "1" --> "*" 医師:所属 >
医師 "1 担当医" ---> "患者 *" 患者:担当 >
患者 "1"---"*" 診察記録
医師 "1 作成者" ----> "作成物 *" 診察記録:作成 >

@enduml