@startuml ユースケース図
left to right direction
actor 利用者#DDDDDD;line:black;line.bold;

rectangle ホテル宿泊予約 {
usecase (<u>予約</u>\nextention points\nキャンペーン期間) as reserve
usecase キャンペーン価格にする
usecase ログイン
}
reserve <.. キャンペーン価格にする : << extend >>
reserve ..> ログイン :<< include >>
利用者 --> reserve

@enduml