@startuml 6-3ステートマシン図
[*] --right-> メニュ :接続
メニュ -down-> 予約と確認 :予約と確認\nボタンを押す
メニュ <-down-- 予約と確認 :取消\nボタンを押す

メニュ <-up- あなたの順番 :メニュへ\nボタンを押す

予約と確認 -> あなたの順番 :登録ボタンを押す
予約と確認 -> あなたの順番 :確認ボタンを押す

メニュ <-down-- 今の順番 :メニュへボタン\nを押す
メニュ --down-> 今の順番 :今の順番ボタン\nを押す

メニュ --right-> [*]

@enduml