@startuml 6-1クラス図
class ライトセンサー{
}

class 光センサー{
}

class 右モータ{
}

class 左モータ{
}

class CPU{
}

class 電源SW{
}

ライトセンサー "1" *-- "1" 光センサー
ライトセンサー "1" *-- "1" 右モータ
ライトセンサー "1" *-- "1" 左モータ
ライトセンサー "1" *-- "1" CPU
ライトセンサー "1" *-- "1" 電源SW

@enduml