@startuml ユースケース図
left to right direction

actor 人事担当者#DDDDDD;line:black;line.bold;
actor 社員#DDDDDD;line:black;line.bold;

rectangle 販売管理システム {

usecase (社員情報を登録) as case1
usecase (社員情報を参照) as case2
}

人事担当者 --> case1
社員 --> case2

@enduml