@startuml ユースケース図
left to right direction

actor 鈴木さん#DDDDDD;line:black;line.bold;
actor 田中さん#DDDDDD;line:black;line.bold;

rectangle 販売管理システム {

usecase 注文商品を確認
usecase 出荷状況を登録
}

鈴木さん --> 注文商品を確認
田中さん --> 出荷状況を登録

@enduml